name = "Bokeh"
uuid = "b7fe046f-2d24-4718-8c03-fdde6cae2a8c"
authors = ["Pol d'Avezac <pdavezac@yahoo.fr>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
